name: Format C++

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -iname "*.cpp" -o -iname "*.h" -o -iname "*.hpp" | xargs clang-format -i

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: 🎨 auto format C++ code with clang-format"
          file_pattern: "*.cpp *.h *.hpp"
