name: Auto Sync & Format

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # 1. 安装并运行 C++ 格式化
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -iname "*.cpp" -o -iname "*.h" -o -iname "*.hpp" | xargs -r clang-format -i

      # 2. 运行 README 自动整理脚本
      - name: Set execute permission for script
        run: chmod +x ./generate_index.sh

      - name: Run script to organize and update README
        run: ./generate_index.sh

      # 3. 统一提交并推送所有变动 (格式化 + README)
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: 🎨 auto format C++ and 📝 update README"
          file_pattern: "."
